//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shipping.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.newegg.com", ConfigurationName="ServiceReference1.OnTracServiceSoap")]
    public interface OnTracServiceSoap {
        
        // CODEGEN: Generating message contract since element name shipmentRequest from namespace http://www.newegg.com is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.newegg.com/Request", ReplyAction="*")]
        Shipping.ServiceReference1.RequestResponse Request(Shipping.ServiceReference1.RequestRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Request", Namespace="http://www.newegg.com", Order=0)]
        public Shipping.ServiceReference1.RequestRequestBody Body;
        
        public RequestRequest() {
        }
        
        public RequestRequest(Shipping.ServiceReference1.RequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.newegg.com")]
    public partial class RequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shipmentRequest;
        
        public RequestRequestBody() {
        }
        
        public RequestRequestBody(string shipmentRequest) {
            this.shipmentRequest = shipmentRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RequestResponse", Namespace="http://www.newegg.com", Order=0)]
        public Shipping.ServiceReference1.RequestResponseBody Body;
        
        public RequestResponse() {
        }
        
        public RequestResponse(Shipping.ServiceReference1.RequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.newegg.com")]
    public partial class RequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RequestResult;
        
        public RequestResponseBody() {
        }
        
        public RequestResponseBody(string RequestResult) {
            this.RequestResult = RequestResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OnTracServiceSoapChannel : Shipping.ServiceReference1.OnTracServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OnTracServiceSoapClient : System.ServiceModel.ClientBase<Shipping.ServiceReference1.OnTracServiceSoap>, Shipping.ServiceReference1.OnTracServiceSoap {
        
        public OnTracServiceSoapClient() {
        }
        
        public OnTracServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OnTracServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnTracServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OnTracServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Shipping.ServiceReference1.RequestResponse Shipping.ServiceReference1.OnTracServiceSoap.Request(Shipping.ServiceReference1.RequestRequest request) {
            return base.Channel.Request(request);
        }
        
        public string Request(string shipmentRequest) {
            Shipping.ServiceReference1.RequestRequest inValue = new Shipping.ServiceReference1.RequestRequest();
            inValue.Body = new Shipping.ServiceReference1.RequestRequestBody();
            inValue.Body.shipmentRequest = shipmentRequest;
            Shipping.ServiceReference1.RequestResponse retVal = ((Shipping.ServiceReference1.OnTracServiceSoap)(this)).Request(inValue);
            return retVal.Body.RequestResult;
        }
    }
}
