//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SamplesApp.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PDALoginInfo", Namespace="http://schemas.datacontract.org/2004/07/Newegg.OZZO.WMS.Service.Domain.Model.Publ" +
        "icManagement")]
    [System.SerializableAttribute()]
    public partial class PDALoginInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmployeeIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IPAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] UsedUtilityRightListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WarehouseNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkStationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationName {
            get {
                return this.ApplicationNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationNameField, value) != true)) {
                    this.ApplicationNameField = value;
                    this.RaisePropertyChanged("ApplicationName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeID {
            get {
                return this.EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.EmployeeIDField, value) != true)) {
                    this.EmployeeIDField = value;
                    this.RaisePropertyChanged("EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IPAddress {
            get {
                return this.IPAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.IPAddressField, value) != true)) {
                    this.IPAddressField = value;
                    this.RaisePropertyChanged("IPAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PIN {
            get {
                return this.PINField;
            }
            set {
                if ((object.ReferenceEquals(this.PINField, value) != true)) {
                    this.PINField = value;
                    this.RaisePropertyChanged("PIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] UsedUtilityRightList {
            get {
                return this.UsedUtilityRightListField;
            }
            set {
                if ((object.ReferenceEquals(this.UsedUtilityRightListField, value) != true)) {
                    this.UsedUtilityRightListField = value;
                    this.RaisePropertyChanged("UsedUtilityRightList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WarehouseNumber {
            get {
                return this.WarehouseNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseNumberField, value) != true)) {
                    this.WarehouseNumberField = value;
                    this.RaisePropertyChanged("WarehouseNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkStation {
            get {
                return this.WorkStationField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkStationField, value) != true)) {
                    this.WorkStationField = value;
                    this.RaisePropertyChanged("WorkStation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnLoginInfo", Namespace="http://schemas.datacontract.org/2004/07/Newegg.OZZO.WMS.Service.Domain.Model.Publ" +
        "icManagement")]
    [System.SerializableAttribute()]
    public partial class ReturnLoginInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string m_AppIDField;
        
        private System.DateTime m_DealDateField;
        
        private string m_EmployeeIDField;
        
        private string m_ErrReasonsField;
        
        private bool m_IsQCModeField;
        
        private int m_IsSuccessField;
        
        private string m_NickNameField;
        
        private SamplesApp.ServiceReference1.MobileURLConfiguration[] m_URLConfigurationListField;
        
        private string m_UserIDField;
        
        private string m_UserNameField;
        
        private string[] m_WHListField;
        
        private SamplesApp.ServiceReference1.KeyStoneAttribute[] m_keyStoneAttributeListField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_AppID {
            get {
                return this.m_AppIDField;
            }
            set {
                if ((object.ReferenceEquals(this.m_AppIDField, value) != true)) {
                    this.m_AppIDField = value;
                    this.RaisePropertyChanged("m_AppID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.DateTime m_DealDate {
            get {
                return this.m_DealDateField;
            }
            set {
                if ((this.m_DealDateField.Equals(value) != true)) {
                    this.m_DealDateField = value;
                    this.RaisePropertyChanged("m_DealDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_EmployeeID {
            get {
                return this.m_EmployeeIDField;
            }
            set {
                if ((object.ReferenceEquals(this.m_EmployeeIDField, value) != true)) {
                    this.m_EmployeeIDField = value;
                    this.RaisePropertyChanged("m_EmployeeID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_ErrReasons {
            get {
                return this.m_ErrReasonsField;
            }
            set {
                if ((object.ReferenceEquals(this.m_ErrReasonsField, value) != true)) {
                    this.m_ErrReasonsField = value;
                    this.RaisePropertyChanged("m_ErrReasons");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool m_IsQCMode {
            get {
                return this.m_IsQCModeField;
            }
            set {
                if ((this.m_IsQCModeField.Equals(value) != true)) {
                    this.m_IsQCModeField = value;
                    this.RaisePropertyChanged("m_IsQCMode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int m_IsSuccess {
            get {
                return this.m_IsSuccessField;
            }
            set {
                if ((this.m_IsSuccessField.Equals(value) != true)) {
                    this.m_IsSuccessField = value;
                    this.RaisePropertyChanged("m_IsSuccess");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_NickName {
            get {
                return this.m_NickNameField;
            }
            set {
                if ((object.ReferenceEquals(this.m_NickNameField, value) != true)) {
                    this.m_NickNameField = value;
                    this.RaisePropertyChanged("m_NickName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SamplesApp.ServiceReference1.MobileURLConfiguration[] m_URLConfigurationList {
            get {
                return this.m_URLConfigurationListField;
            }
            set {
                if ((object.ReferenceEquals(this.m_URLConfigurationListField, value) != true)) {
                    this.m_URLConfigurationListField = value;
                    this.RaisePropertyChanged("m_URLConfigurationList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_UserID {
            get {
                return this.m_UserIDField;
            }
            set {
                if ((object.ReferenceEquals(this.m_UserIDField, value) != true)) {
                    this.m_UserIDField = value;
                    this.RaisePropertyChanged("m_UserID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_UserName {
            get {
                return this.m_UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.m_UserNameField, value) != true)) {
                    this.m_UserNameField = value;
                    this.RaisePropertyChanged("m_UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string[] m_WHList {
            get {
                return this.m_WHListField;
            }
            set {
                if ((object.ReferenceEquals(this.m_WHListField, value) != true)) {
                    this.m_WHListField = value;
                    this.RaisePropertyChanged("m_WHList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SamplesApp.ServiceReference1.KeyStoneAttribute[] m_keyStoneAttributeList {
            get {
                return this.m_keyStoneAttributeListField;
            }
            set {
                if ((object.ReferenceEquals(this.m_keyStoneAttributeListField, value) != true)) {
                    this.m_keyStoneAttributeListField = value;
                    this.RaisePropertyChanged("m_keyStoneAttributeList");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MobileURLConfiguration", Namespace="http://schemas.datacontract.org/2004/07/Newegg.OZZO.WMS.Service.Domain.Model.Publ" +
        "icManagement")]
    [System.SerializableAttribute()]
    public partial class MobileURLConfiguration : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string m_IPField;
        
        private string m_KeyField;
        
        private string m_PortField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_IP {
            get {
                return this.m_IPField;
            }
            set {
                if ((object.ReferenceEquals(this.m_IPField, value) != true)) {
                    this.m_IPField = value;
                    this.RaisePropertyChanged("m_IP");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_Key {
            get {
                return this.m_KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.m_KeyField, value) != true)) {
                    this.m_KeyField = value;
                    this.RaisePropertyChanged("m_Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string m_Port {
            get {
                return this.m_PortField;
            }
            set {
                if ((object.ReferenceEquals(this.m_PortField, value) != true)) {
                    this.m_PortField = value;
                    this.RaisePropertyChanged("m_Port");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KeyStoneAttribute", Namespace="http://schemas.datacontract.org/2004/07/Newegg.WMS.AuthorizationLib.Entity")]
    [System.SerializableAttribute()]
    public partial class KeyStoneAttribute : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string WarehouseNumberk__BackingFieldField;
        
        private SamplesApp.ServiceReference1.RightAbility[] m_FunctionAbilitysField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<WarehouseNumber>k__BackingField", IsRequired=true)]
        public string WarehouseNumberk__BackingField {
            get {
                return this.WarehouseNumberk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.WarehouseNumberk__BackingFieldField, value) != true)) {
                    this.WarehouseNumberk__BackingFieldField = value;
                    this.RaisePropertyChanged("WarehouseNumberk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public SamplesApp.ServiceReference1.RightAbility[] m_FunctionAbilitys {
            get {
                return this.m_FunctionAbilitysField;
            }
            set {
                if ((object.ReferenceEquals(this.m_FunctionAbilitysField, value) != true)) {
                    this.m_FunctionAbilitysField = value;
                    this.RaisePropertyChanged("m_FunctionAbilitys");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RightAbility", Namespace="http://schemas.datacontract.org/2004/07/Newegg.WMS.AuthorizationLib.Entity")]
    [System.SerializableAttribute()]
    public partial class RightAbility : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string IDk__BackingFieldField;
        
        private string Namek__BackingFieldField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<ID>k__BackingField", IsRequired=true)]
        public string IDk__BackingField {
            get {
                return this.IDk__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.IDk__BackingFieldField, value) != true)) {
                    this.IDk__BackingFieldField = value;
                    this.RaisePropertyChanged("IDk__BackingField");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Name="<Name>k__BackingField", IsRequired=true)]
        public string Namek__BackingField {
            get {
                return this.Namek__BackingFieldField;
            }
            set {
                if ((object.ReferenceEquals(this.Namek__BackingFieldField, value) != true)) {
                    this.Namek__BackingFieldField = value;
                    this.RaisePropertyChanged("Namek__BackingField");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Distance_Location_Result", Namespace="http://schemas.datacontract.org/2004/07/Newegg.OZZO.WMS.Service.Domain.Model.Ware" +
        "houseManagement")]
    [System.SerializableAttribute()]
    public partial class Distance_Location_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DefaultDistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DefaultDistanceIncludeWeightField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DistanceToStartField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SortLocationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DefaultDistance {
            get {
                return this.DefaultDistanceField;
            }
            set {
                if ((this.DefaultDistanceField.Equals(value) != true)) {
                    this.DefaultDistanceField = value;
                    this.RaisePropertyChanged("DefaultDistance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DefaultDistanceIncludeWeight {
            get {
                return this.DefaultDistanceIncludeWeightField;
            }
            set {
                if ((this.DefaultDistanceIncludeWeightField.Equals(value) != true)) {
                    this.DefaultDistanceIncludeWeightField = value;
                    this.RaisePropertyChanged("DefaultDistanceIncludeWeight");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DistanceToStart {
            get {
                return this.DistanceToStartField;
            }
            set {
                if ((this.DistanceToStartField.Equals(value) != true)) {
                    this.DistanceToStartField = value;
                    this.RaisePropertyChanged("DistanceToStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Location {
            get {
                return this.LocationField;
            }
            set {
                if ((object.ReferenceEquals(this.LocationField, value) != true)) {
                    this.LocationField = value;
                    this.RaisePropertyChanged("Location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SortLocation {
            get {
                return this.SortLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.SortLocationField, value) != true)) {
                    this.SortLocationField = value;
                    this.RaisePropertyChanged("SortLocation");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReplenishmentTask", Namespace="http://schemas.datacontract.org/2004/07/Newegg.OZZO.WMS.Service.Domain.Model.Publ" +
        "icManagement")]
    [System.SerializableAttribute()]
    public partial class ReplenishmentTask : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OwnerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickingLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StatusCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TaskIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNumberField, value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Owner {
            get {
                return this.OwnerField;
            }
            set {
                if ((object.ReferenceEquals(this.OwnerField, value) != true)) {
                    this.OwnerField = value;
                    this.RaisePropertyChanged("Owner");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickingLocation {
            get {
                return this.PickingLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.PickingLocationField, value) != true)) {
                    this.PickingLocationField = value;
                    this.RaisePropertyChanged("PickingLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Status {
            get {
                return this.StatusField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusField, value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StatusCode {
            get {
                return this.StatusCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.StatusCodeField, value) != true)) {
                    this.StatusCodeField = value;
                    this.RaisePropertyChanged("StatusCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TaskID {
            get {
                return this.TaskIDField;
            }
            set {
                if ((this.TaskIDField.Equals(value) != true)) {
                    this.TaskIDField = value;
                    this.RaisePropertyChanged("TaskID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/Newegg.OZZO.WMS.Service.Domain.Model.Publ" +
        "icManagement")]
    [System.SerializableAttribute()]
    public partial class Item : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ItemNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PickingLocationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PriorityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ToZoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemNumber {
            get {
                return this.ItemNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.ItemNumberField, value) != true)) {
                    this.ItemNumberField = value;
                    this.RaisePropertyChanged("ItemNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PickingLocation {
            get {
                return this.PickingLocationField;
            }
            set {
                if ((object.ReferenceEquals(this.PickingLocationField, value) != true)) {
                    this.PickingLocationField = value;
                    this.RaisePropertyChanged("PickingLocation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Priority {
            get {
                return this.PriorityField;
            }
            set {
                if ((this.PriorityField.Equals(value) != true)) {
                    this.PriorityField = value;
                    this.RaisePropertyChanged("Priority");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ToZone {
            get {
                return this.ToZoneField;
            }
            set {
                if ((object.ReferenceEquals(this.ToZoneField, value) != true)) {
                    this.ToZoneField = value;
                    this.RaisePropertyChanged("ToZone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IPublicManagement")]
    public interface IPublicManagement {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/PDALoginAndGetWarehouse", ReplyAction="http://tempuri.org/IPublicManagement/PDALoginAndGetWarehouseResponse")]
        SamplesApp.ServiceReference1.ReturnLoginInfo PDALoginAndGetWarehouse(SamplesApp.ServiceReference1.PDALoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/PDALoginAndGetWarehouse", ReplyAction="http://tempuri.org/IPublicManagement/PDALoginAndGetWarehouseResponse")]
        System.Threading.Tasks.Task<SamplesApp.ServiceReference1.ReturnLoginInfo> PDALoginAndGetWarehouseAsync(SamplesApp.ServiceReference1.PDALoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/GetLocationDistances", ReplyAction="http://tempuri.org/IPublicManagement/GetLocationDistancesResponse")]
        SamplesApp.ServiceReference1.Distance_Location_Result[] GetLocationDistances(string whNo, string startLocation, string[] locations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/GetLocationDistances", ReplyAction="http://tempuri.org/IPublicManagement/GetLocationDistancesResponse")]
        System.Threading.Tasks.Task<SamplesApp.ServiceReference1.Distance_Location_Result[]> GetLocationDistancesAsync(string whNo, string startLocation, string[] locations);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/HasActiveInventory", ReplyAction="http://tempuri.org/IPublicManagement/HasActiveInventoryResponse")]
        bool HasActiveInventory(string itemNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/HasActiveInventory", ReplyAction="http://tempuri.org/IPublicManagement/HasActiveInventoryResponse")]
        System.Threading.Tasks.Task<bool> HasActiveInventoryAsync(string itemNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/GetOpenReplenishmentTaskList", ReplyAction="http://tempuri.org/IPublicManagement/GetOpenReplenishmentTaskListResponse")]
        SamplesApp.ServiceReference1.ReplenishmentTask[] GetOpenReplenishmentTaskList(string[] itemNumbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/GetOpenReplenishmentTaskList", ReplyAction="http://tempuri.org/IPublicManagement/GetOpenReplenishmentTaskListResponse")]
        System.Threading.Tasks.Task<SamplesApp.ServiceReference1.ReplenishmentTask[]> GetOpenReplenishmentTaskListAsync(string[] itemNumbers);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/GenerateReplenishmentTask", ReplyAction="http://tempuri.org/IPublicManagement/GenerateReplenishmentTaskResponse")]
        SamplesApp.ServiceReference1.ReplenishmentTask[] GenerateReplenishmentTask(SamplesApp.ServiceReference1.Item[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/GenerateReplenishmentTask", ReplyAction="http://tempuri.org/IPublicManagement/GenerateReplenishmentTaskResponse")]
        System.Threading.Tasks.Task<SamplesApp.ServiceReference1.ReplenishmentTask[]> GenerateReplenishmentTaskAsync(SamplesApp.ServiceReference1.Item[] items);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/GenerateReplenishmentTaskWithTaskOwner", ReplyAction="http://tempuri.org/IPublicManagement/GenerateReplenishmentTaskWithTaskOwnerRespon" +
            "se")]
        SamplesApp.ServiceReference1.ReplenishmentTask[] GenerateReplenishmentTaskWithTaskOwner(SamplesApp.ServiceReference1.Item[] items, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/GenerateReplenishmentTaskWithTaskOwner", ReplyAction="http://tempuri.org/IPublicManagement/GenerateReplenishmentTaskWithTaskOwnerRespon" +
            "se")]
        System.Threading.Tasks.Task<SamplesApp.ServiceReference1.ReplenishmentTask[]> GenerateReplenishmentTaskWithTaskOwnerAsync(SamplesApp.ServiceReference1.Item[] items, string userId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/MoveOutItemAndCreatePutawayTask", ReplyAction="http://tempuri.org/IPublicManagement/MoveOutItemAndCreatePutawayTaskResponse")]
        int MoveOutItemAndCreatePutawayTask(string warehouseNumber, string itemNumber, string fromLocation, string userID, int Quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/MoveOutItemAndCreatePutawayTask", ReplyAction="http://tempuri.org/IPublicManagement/MoveOutItemAndCreatePutawayTaskResponse")]
        System.Threading.Tasks.Task<int> MoveOutItemAndCreatePutawayTaskAsync(string warehouseNumber, string itemNumber, string fromLocation, string userID, int Quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/PDAWriteSuccessLoginLog", ReplyAction="http://tempuri.org/IPublicManagement/PDAWriteSuccessLoginLogResponse")]
        void PDAWriteSuccessLoginLog(SamplesApp.ServiceReference1.PDALoginInfo loginInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPublicManagement/PDAWriteSuccessLoginLog", ReplyAction="http://tempuri.org/IPublicManagement/PDAWriteSuccessLoginLogResponse")]
        System.Threading.Tasks.Task PDAWriteSuccessLoginLogAsync(SamplesApp.ServiceReference1.PDALoginInfo loginInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPublicManagementChannel : SamplesApp.ServiceReference1.IPublicManagement, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PublicManagementClient : System.ServiceModel.ClientBase<SamplesApp.ServiceReference1.IPublicManagement>, SamplesApp.ServiceReference1.IPublicManagement {
        
        public PublicManagementClient() {
        }
        
        public PublicManagementClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PublicManagementClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicManagementClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PublicManagementClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SamplesApp.ServiceReference1.ReturnLoginInfo PDALoginAndGetWarehouse(SamplesApp.ServiceReference1.PDALoginInfo loginInfo) {
            return base.Channel.PDALoginAndGetWarehouse(loginInfo);
        }
        
        public System.Threading.Tasks.Task<SamplesApp.ServiceReference1.ReturnLoginInfo> PDALoginAndGetWarehouseAsync(SamplesApp.ServiceReference1.PDALoginInfo loginInfo) {
            return base.Channel.PDALoginAndGetWarehouseAsync(loginInfo);
        }
        
        public SamplesApp.ServiceReference1.Distance_Location_Result[] GetLocationDistances(string whNo, string startLocation, string[] locations) {
            return base.Channel.GetLocationDistances(whNo, startLocation, locations);
        }
        
        public System.Threading.Tasks.Task<SamplesApp.ServiceReference1.Distance_Location_Result[]> GetLocationDistancesAsync(string whNo, string startLocation, string[] locations) {
            return base.Channel.GetLocationDistancesAsync(whNo, startLocation, locations);
        }
        
        public bool HasActiveInventory(string itemNumber) {
            return base.Channel.HasActiveInventory(itemNumber);
        }
        
        public System.Threading.Tasks.Task<bool> HasActiveInventoryAsync(string itemNumber) {
            return base.Channel.HasActiveInventoryAsync(itemNumber);
        }
        
        public SamplesApp.ServiceReference1.ReplenishmentTask[] GetOpenReplenishmentTaskList(string[] itemNumbers) {
            return base.Channel.GetOpenReplenishmentTaskList(itemNumbers);
        }
        
        public System.Threading.Tasks.Task<SamplesApp.ServiceReference1.ReplenishmentTask[]> GetOpenReplenishmentTaskListAsync(string[] itemNumbers) {
            return base.Channel.GetOpenReplenishmentTaskListAsync(itemNumbers);
        }
        
        public SamplesApp.ServiceReference1.ReplenishmentTask[] GenerateReplenishmentTask(SamplesApp.ServiceReference1.Item[] items) {
            return base.Channel.GenerateReplenishmentTask(items);
        }
        
        public System.Threading.Tasks.Task<SamplesApp.ServiceReference1.ReplenishmentTask[]> GenerateReplenishmentTaskAsync(SamplesApp.ServiceReference1.Item[] items) {
            return base.Channel.GenerateReplenishmentTaskAsync(items);
        }
        
        public SamplesApp.ServiceReference1.ReplenishmentTask[] GenerateReplenishmentTaskWithTaskOwner(SamplesApp.ServiceReference1.Item[] items, string userId) {
            return base.Channel.GenerateReplenishmentTaskWithTaskOwner(items, userId);
        }
        
        public System.Threading.Tasks.Task<SamplesApp.ServiceReference1.ReplenishmentTask[]> GenerateReplenishmentTaskWithTaskOwnerAsync(SamplesApp.ServiceReference1.Item[] items, string userId) {
            return base.Channel.GenerateReplenishmentTaskWithTaskOwnerAsync(items, userId);
        }
        
        public int MoveOutItemAndCreatePutawayTask(string warehouseNumber, string itemNumber, string fromLocation, string userID, int Quantity) {
            return base.Channel.MoveOutItemAndCreatePutawayTask(warehouseNumber, itemNumber, fromLocation, userID, Quantity);
        }
        
        public System.Threading.Tasks.Task<int> MoveOutItemAndCreatePutawayTaskAsync(string warehouseNumber, string itemNumber, string fromLocation, string userID, int Quantity) {
            return base.Channel.MoveOutItemAndCreatePutawayTaskAsync(warehouseNumber, itemNumber, fromLocation, userID, Quantity);
        }
        
        public void PDAWriteSuccessLoginLog(SamplesApp.ServiceReference1.PDALoginInfo loginInfo) {
            base.Channel.PDAWriteSuccessLoginLog(loginInfo);
        }
        
        public System.Threading.Tasks.Task PDAWriteSuccessLoginLogAsync(SamplesApp.ServiceReference1.PDALoginInfo loginInfo) {
            return base.Channel.PDAWriteSuccessLoginLogAsync(loginInfo);
        }
    }
}
